# Generated by Django 4.2.11 on 2024-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
