# Generated by Django 4.2.11 on 2024-04-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_is_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
