# Generated by Django 4.2.11 on 2024-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
