# Generated by Django 4.2.11 on 2024-04-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_ended_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user_id',
            new_name='user',
        ),
    ]
