# Generated by Django 4.2.11 on 2024-04-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_descriptions_alter_workout_user'),
        ('exercise', '0002_rename_exercise_name_exercise_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='exercise.exerciselist'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workout'),
        ),
    ]
